[package]
name = "tor-consdiff"
version = "0.2.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Handle the consensus-diff format used in the Tor directory protocol"
keywords = [ "tor", "arti", "diff" ]
categories = [ "parser-implementations", "network-programming" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
slow-diff-apply = []

[dependencies]

tor-llcrypto = { path="../tor-llcrypto", version = "0.2.0"}

digest = "0.10.0"
hex = "0.4"
thiserror = "1"
