[package]
name = "arti-client"
version = "0.8.1"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Library for connecting to the Tor network as an anonymous client"
keywords = ["tor", "arti", "privacy", "anonymity", "networking"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["tokio", "rustls", "compression"]
# "full" is a top-level selector that turns on every feature, _EXCEPT FOR_:
#   * Features that are experimental or unstable
#   * Features that are testing-only
#   * Features which are select a particular implementation or build flag and
#     which therefore are not strictly additive.
#   * Features which may introduce unnecessary licensing restrictions.
full = [
    "tokio",
    "async-std",
    "rustls",
    "compression",
    "bridge-client",
    "pt-client",
    "tor-rtcompat/full",
    "tor-proto/full",
    "tor-netdoc/full",
    "tor-dirmgr/full"
]

async-std = ["tor-rtcompat/async-std"]
bridge-client = ["tor-guardmgr/bridge-client", "tor-dirmgr/bridge-client"]
tokio = ["tor-rtcompat/tokio", "tor-proto/tokio"]
native-tls = ["tor-rtcompat/native-tls"]
pt-client = ["bridge-client", "tor-chanmgr/pt-client", "tor-guardmgr/pt-client", "tor-ptmgr"]
rustls = ["tor-rtcompat/rustls"]

# depends directly on tor-rtcompat/static so native-tls doesn't get automatically included
static = ["static-sqlite", "tor-rtcompat/static"]
static-sqlite = ["tor-dirmgr/static"]
static-native-tls = ["tor-rtcompat/static", "native-tls"]

accel-sha1-asm = ["tor-llcrypto/with-sha1-asm"]
accel-openssl = ["tor-llcrypto/with-openssl"]

compression = ["tor-dirmgr/compression"]

experimental = [
    "dirfilter",
    "experimental-api",
    "error_detail",
    "onion-client",
    "tor-proto/experimental",
    "tor-cell/experimental",
    "tor-checkable/experimental",
    "tor-netdoc/experimental",
    "tor-dirmgr/experimental",
    "tor-circmgr/experimental",
] # Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = []
dirfilter = ["tor-dirmgr/dirfilter"]
error_detail = []
onion-client = ["tor-hscrypto"]

[dependencies]
cfg-if = "1.0.0"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
derive_more = "0.99.3"
directories = "4"
educe = "0.4.6"
fs-mistrust = { path = "../fs-mistrust", version = "0.6.0", features = ["serde"] }
futures = "0.3.14"
hostname-validator = "1.1.1"
humantime-serde = "1.1.1"
libc = "0.2"
pin-project = "1"
postage = { version = "0.5.0", default-features = false, features = ["futures-traits"] }
safelog = { path = "../safelog", version = "0.2.1" }
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.5.0" }
tor-cell = { path = "../tor-cell", version = "0.8.0" }
tor-chanmgr = { path = "../tor-chanmgr", version = "0.8.1" }
tor-checkable = { path = "../tor-checkable", version = "0.4.0" }
tor-circmgr = { path = "../tor-circmgr", version = "0.7.1" }
tor-config = { path = "../tor-config", version = "0.7.1" }
tor-dirmgr = { path = "../tor-dirmgr", version = "0.9.1", default-features = false, features = [
    "mmap",
] }
tor-error = { path = "../tor-error", version = "0.4.1" }
tor-guardmgr = { path = "../tor-guardmgr", version = "0.8.1" }
tor-hscrypto = { path = "../tor-hscrypto", version = "0.1.0", optional = true }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.4.1" }
tor-netdir = { path = "../tor-netdir", version = "0.7.1" }
tor-netdoc = { path = "../tor-netdoc", version = "0.6.1" }
tor-persist = { path = "../tor-persist", version = "0.6.1" }
tor-proto = { path = "../tor-proto", version = "0.8.1" }
tor-ptmgr = { path = "../tor-ptmgr", version = "0.2.1", optional = true }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.8.1" }
tracing = "0.1.18"

[dev-dependencies]
anyhow = "1.0.23"
once_cell = "1.9"
pin-project = "1"
tempfile = "3.3"
tokio-crate = { package = "tokio", version = "1.7", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "net",
    "time",
    "macros",
] }
tokio-util = { version = "0.7.0", features = ["compat"] }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.8.1", features = ["tokio", "native-tls"] }
tracing-subscriber = "0.3.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
