# Configuration file used when running api integration tests with webdriver.

[general]
host = "0.0.0.0"
port = 8081
message_max_time = 10 # In ms.
verbose_log = true
log_path = "/tmp"
remote_services_config = "./remote/config.toml"
remote_services_path = "./remote"
socket_path = "/tmp/api-daemon-socket"

[http]
root_path = "../prebuilts/http_root"

[telemetry]
enabled = false
token_uri = "https://api.stage.kaiostech.com/v3.0/applications"
metrics_uri = "https://api.stage.kaiostech.com/v3.0/apps/metrics"

[vhost]
root_path = "../prebuilts/http_root/webapps/vroot"
# This CSP is more permissive than for regular apps, to allow inline scripts in tests.
# DON'T REUSE IT IN OTHER CONTEXTS.
csp = "default-src * data: blob:; script-src 'self' http://127.0.0.1:8081 'unsafe-inline'; object-src 'none'; style-src 'self' 'unsafe-inline' http://127.0.0.1:8081"

[apps_service]
root_path = "../tests/webapps"
data_path = "../prebuilts/http_root/webapps"
uds_path = "/tmp/apps_service_uds.sock"
cert_type = "test"
updater_socket = "/tmp/updater_socket"
user_agent = "Mozilla/5.0 (Mobile; rv:90.0) Gecko/90.0 Firefox/90.0 KAIOS/3.2"
allow_remove_preloaded = true
