[package]
name = "tor-netdir"
version = "0.6.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Types to represent and use a Tor network directory"
keywords = ["tor", "arti"]
categories = ["network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []

experimental = ["experimental-api"]

# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = []

# Enable testing-only APIs.  APIs under this feature are not
# covered by semver.
testing = ["hex", "hex-literal", "tor-netdoc/build_docs"]

[dependencies]
bitflags = "1"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
derive_more = "0.99"
futures = "0.3.14"
hex = { version = "0.4", optional = true }
hex-literal = { version = "0.3", optional = true }
rand = "0.8"
serde = { version = "1.0.103", features = ["derive"] }
signature = "1"
static_assertions = "1"
thiserror = "1"
tor-checkable = { path = "../tor-checkable", version = "0.3.0" }
tor-config = { path = "../tor-config", version = "0.6.0" }
tor-error = { path = "../tor-error", version = "0.3.2" }
tor-linkspec = { path = "../tor-linkspec", version = "0.5.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.3.4" }
tor-netdoc = { path = "../tor-netdoc", version = "0.5.1" }
tor-protover = { path = "../tor-protover", version = "0.3.0" }
tor-units = { path = "../tor-units", version = "0.3.1" }
tracing = "0.1.18"

[dev-dependencies]
float_eq = "1.0.0"
hex = "0.4"
hex-literal = "0.3"
rand_chacha = "0.3"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.4.0" }
tor-netdoc = { path = "../tor-netdoc", version = "0.5.1", features = ["build_docs"] }
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
