[package]
name = "tor-cert"
version = "0.5.1"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Non-standard certificate formats used by Tor"
keywords = ["tor", "arti", "certificate"]
categories = ["parser-implementations"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
experimental = ["encode"]
encode = ["derive_builder"]

[dependencies]
caret = { path = "../caret", version = "0.2.0" }
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti", optional = true }
digest = "0.10.0"
signature = "1"
thiserror = "1"
tor-bytes = { path = "../tor-bytes", version = "0.5.1" }
tor-checkable = { path = "../tor-checkable", version = "0.3.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.3.4" }

[dev-dependencies]
base64 = "0.13.0"
hex-literal = "0.3"
rand = "0.8"
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
