name: Build
on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: cargo build
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust toolchain
        run: rustup install stable
      
      - name: Configure CI cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        run: rustup install stable
      
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust toolchain
        run: rustup install stable
      
      - name: Setup CI cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy

