[package]
name = "android_utils"
version = "0.1.0"
authors = ["Fabrice Desré <fabrice@desre.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
log = "0.4"
thiserror = "1.0"

[target.'cfg(not(target_os = "macos"))'.dependencies]
procfs = "0.10"
