[package]
name = "binder"
version = "0.1.0"
authors = ["Fabrice Desré <fabrice@desre.org>"]
edition = "2018"
license = "Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
binder_ndk_sys = { path = "../sys" }
downcast-rs = "1.2"
libc = "0.2" 